### ISSUE TITLE
GatewayJS returns the RenVM transaction to the developer

### ISSUE THREAD

**Issue by noiach** [renproject/gateway-js#7]
### Description

GatewayJS must always return the RenVM transaction. This allows developers to catch it and do anything with it. Specifically, it allows developers to submit it to a gas-less or conf-less system of their choosing. It also allows them to use a Web3 provider of their choosing (although it is possible to embed this into GatewayJS in a way that developers can still control). See #5.

### Design

Right now, GatewayJS's main function, `.open`, exposes no control over the flow of shifting in. In order to provide more flexibility, developers should have the option of not providing a Web3 provider, resulting in GatewayJS returning the RenVM transaction when available, instead of submitting it to Ethereum. GatewayJS should offer a follow-up function to transform this RenVM transaction into a respective Ethereum transaction (ready to be submitted through the normal Web3 ways).

### Checklist

- [ ] If the developer doesn't provide a web3 provider, the RenVM transaction is returned to the developer when it's first available. An option is exposed to control if this is when the signature is available or before then.
- [ ] GatewayJS offers a `.buildEthTransaction` function that transforms the RenVM transaction into an Ethereum transaction.

**Comment by loongy** [comment]
>Instead, as soon as the RenVM transaction is available, it will be returned to the developer

This doesn't necessarily have to be the case. There are actually a few options here:

1. GatewayJS is initialised with a Web3 provider. After returning from the iFrame, the GatewayJS `open` function will automatically construct the relevant Ethereum transaction and send it to the Web3 provider.
2. GatewayJS is not initialised with a Web3 provider. After returning from the iFrame, the GatewayJS `open` function returns the RenVM transaction. GatewayJS offers a follow-up function to transform this RenVM transaction into a respective Ethereum transaction (ready to be submitted through the normal Web3 ways).
3. GatewayJS offers both (1) (calling it `openAndSubmit`) and (2) (calling it `open`).

**Comment by noiach** [comment]
:+1: I've updated the issue to include (1) and (2). Regarding (3), I think it might be simpler to have one function with more config options, than multiple functions.
